### ISSUE TITLE
Remove the custom allocator (alloc.c)

### ISSUE THREAD

**Issue by DerDakon** [notqmail/notqmail#112]
What does this do at all? It has a 4096 byte static allocation and serves small memory blocks from there as long as they fit, probably to avoid crappy slow system allocators. I say: kill it. Here are some things I have in mind why we should do it:

 * it's as simple as possible, probably intentional. This makes things like ```alloc_re()``` (i.e. ```realloc()```) inefficient as it does not look if the thing it reallocates is already the last thing in the batch, and simply extends that, or if ```alloc_free()``` has the last block and adds things back to the pool (ideally with zeroing for security reasons).
 * it makes it basically impossible to detect overruns on early small allocations with tools like valgrind, address sanitizer or friends as those allocations never hit ```malloc()```, so are never traced by any custom tools. Any overrun will just go into the next variable, untracable.
 * allocators do their own buffering, alignment, and so on. If they are broken, your system is severely screwed. And if we need more money^H^H^H^Hemory we will hit that buggy allocatator anyway, making things harder to detect as it will only happen on "heavy" memory usage. This is not TruOS, SunOS 1.x or something like that anymore. We expect a reasonably sane OS. Everything else will get us screwed in much more severe ways.
 * it has shown issues when coming close to 4GiB allocations (#37, #109, [older reports](https://marc.info/?l=qmail&m=125213850310173&w=2)). DJB correctly says that an allocation of that size in your mailer shows that you have already done something wrong, but still: 64 bit platforms are the default, so using a 32 bit type to pass allocation sizes is a bug of it's own.
 * why bother at all with writing an allocator?

**Comment by josuah** [comment]
I suppose DJB did encounter unexpected behavior of some malloc he did encounter, maybe a bug even.  That is to be fixed upstream...  

`malloc()` & co's API does not look bad to me, I support having these functions replaced directly as suggested.

**Comment by josuah** [comment]
Reading `alloc.c` again, illustrating what @DerDakon just said:

https://github.com/notqmail/notqmail/blob/master/alloc.c#L9
```C
typedef union { char irrelevant[ALIGNMENT]; double d; } aligned;
static aligned realspace[SPACE / ALIGNMENT];
#define space ((char *) realspace)
static unsigned int avail = SPACE; /* multiple of ALIGNMENT; 0<=avail<=SPACE */
```

The `realspace` or `space` or `SPACE` (macros) are refering to a static buffer in the stack.  In `alloc()`, if a large amount of memory is needed, heap will still be used:

https://github.com/notqmail/notqmail/blob/master/alloc.c#L23-L24
```C
  if (n >= SPACE)
    return m_alloc(n);
```

So `alloc()` might return a pointer to a static buffer from the stack if a small amount of memory is needed.

```C
return space + avail;
```

In `alloc_free()`, care is taken to not call the libc's `free()` on the stack-allocated pointer:

https://github.com/notqmail/notqmail/blob/master/alloc.c#L35-L36
```C
  if (x >= space)
    if (x < space + SPACE)
      return; /* XXX: assuming that pointers are flat */
```

So this is not a custom allocator, rather an extra optimisation over the libc allocator.

This code could go straight to the libc on malloc, as a beforehand optimisation for short buffers. It might be that qmail was slowed down for small buffer allocation on the systems it was being developed and tested on.
