### ISSUE TITLE
qmail-remote: remove CNAME handling in addrmangle

### ISSUE THREAD

**Issue by leahneukirchen** [notqmail/notqmail#120]
Currently, when qmail-remote sends a mail (not to a RELAYHOST) to `foo@bar.org`, and `bar.org` is a CNAME to `quux.org`, addrmangle will rewrite the envelope address to `foo@quux.org`. Aeons ago, this was deemed a good idea. Nowadays, at least Postfix (since version 2 from 2002) and OpenSMTPD (never) don't do it. Sendmail can do it, but apparently doesn't by default.

RFC 5321 (from 2008), Section 5.1 clearly specifies what MTA should do today:

>   The lookup first attempts to locate an MX record associated with the
>  name.  If a CNAME record is found, the resulting name is processed as
>   if it were the initial name.

djb wrote in https://cr.yp.to/im/cname.html:

> Most implementors agree that this feature is not worth the implementation costs. I recommend that, before January 2001, sites stop relying on client-side CNAME translation, so that implementors can safely remove the feature at that time.

It is easy to patch out by considering `flagcname` to be constant zero.

**Comment by leahneukirchen** [comment]
(A result of this brouhaha is that CNAMEs pointing to MXes are quite rare.)

**Comment by DerDakon** [comment]
Care to make a patch?

**Comment by josuah** [comment]
I guess it was common to disable CNAME handling, as it is causing issues on certain situations: https://lists.gt.net/qmail/users/138190

This goes toward "applying patches that everyone applies" and I further approve the changes that Dan Bernstein himself suggested doing (through making dns_cname returning 0).
