### ISSUE TITLE
Consider queue safety on case-insensitive filesystems

### ISSUE THREAD

**Issue by schmonz** [notqmail/notqmail#14]
Mac OS X's default HFS+ filesystem defaults to case-insensitive (and case-preserving).

With a couple small fixes, notqmail will build and installs on a typical OS X system, and casually appears to run fine. But it seems unlikely that DJB was thinking about case-insensitive filesystems when he designed qmail, in particular its guarantees about how the queue behaves.

In pkgsrc, the qmail package warns at install time if the queue is on a case-insensitive filesystem. If we can evaluate the queue code and draw a convincing conclusion, we can either not bother warning or not bother installing.

**Comment by DerDakon** [comment]
I would bet there is no problem: the files in queue get their inode number as names, so all parts of filenames in the queue are just digits.

**Comment by alanpost** [comment]
I agree with @DerDakon.  Files in the queue are numeric, along with their directory entries.  When they are not inode numbers, they are process ids.

It's existentially possible that one of the various queue repair tools introduces a new problem--but even that is unlikely.

Good question, upon investigation not an issue.  I'll resolve this ticket.

**Comment by schmonz** [comment]
Thank you both for taking a look. Nothing to do for us, then. And I've removed the warning from pkgsrc :-)
