### ISSUE TITLE
Regression in 1.08: recipient-address qualification

### ISSUE THREAD

**Issue by schmonz** [notqmail/notqmail#147]
The NetBSD script `/etc/daily` generates two emails to the sysadmin. It's called from `cron` like so:

    22 3 * * * /bin/sh /etc/daily 2>&1 | tee /var/log/daily.out | sendmail -t

In notqmail 1.07 (and netqmail before that), both emails were being addressed `To: root@my.fully.qualified.host.name`.

As of 1.08, one of the emails is instead addressed just `To: root`. Replacing `qmail-inject` with 1.07’s is sufficient to restore the previous behavior.

**Comment by schmonz** [comment]
A minimal `qmail-inject-bug-reproducer`:

```sh
#!/bin/sh

AN_UNQUALIFIED_RECIPIENT=schmonz

host="notqmail-inject-test $(hostname)"
date="now $(date)"

echo "To: ${AN_UNQUALIFIED_RECIPIENT}"
echo "Subject: $host daily output for $date"
echo ""

echo "some daily insecurity output" | \
        mail -s "$host daily insecurity output for $date" ${AN_UNQUALIFIED_RECIPIENT}

echo "some daily output"
```

To run this the same way NetBSD's `/etc/daily` would:

    $ ./qmail-inject-bug-reproducer | sendmail -t

(It needs to be notqmail's `sendmail`, of course.)

This delivers me two messages, one of which has not qualified the `To:` address.

The one with the regression, injected via `mail` -> `sendmail` (options not yet known) -> `qmail-inject -a -- schmonz`:

```
Return-Path: <schmonz@schmonz.com>
Delivered-To: schmonz@miracle-dirt.schmonz.com
Received: (qmail 17228 invoked by uid 1000); 7 Dec 2020 15:28:08 -0000
Date: 7 Dec 2020 15:28:08 -0000
Message-ID: <20201207152808.3822.qmail@miracle-dirt.schmonz.com>
From: schmonz@schmonz.com
To: schmonz
Subject: notqmail-inject-test miracle-dirt.schmonz.com daily insecurity output for now Mon Dec  7 10:28:08 EST 2020

some daily insecurity output
```

And the one that does fully qualify the recipient, injected via `sendmail -t` -> `qmail-inject -H --`:

```
Return-Path: <schmonz@schmonz.com>
Delivered-To: schmonz@miracle-dirt.schmonz.com
Received: (qmail 7610 invoked by uid 1000); 7 Dec 2020 15:28:08 -0000
Date: 7 Dec 2020 15:28:08 -0000
Message-ID: <20201207152808.27560.qmail@miracle-dirt.schmonz.com>
From: schmonz@schmonz.com
To: schmonz@miracle-dirt.schmonz.com
Subject: notqmail-inject-test miracle-dirt.schmonz.com daily output for now Mon Dec  7 10:28:08 EST 2020

some daily output
```

**Comment by schmonz** [comment]
Here's a version that doesn't depend on mail(1) or `sendmail`:

```sh
#!/bin/sh

QMAIL_INJECT=/opt/pkg/bin/qmail-inject

AN_UNQUALIFIED_RECIPIENT=schmonz

doit() {
        local _cmd _msg
        _cmd="$1"
        _msg="$2"
${_cmd} <<EOT
To: ${AN_UNQUALIFIED_RECIPIENT}
Subject: ${_cmd}

${_cmd}
${_msg}
EOT
}

main() {
        doit \
                "${QMAIL_INJECT} -a -- ${AN_UNQUALIFIED_RECIPIENT}" \
                "does NOT fully qualify the To: recipient."
        doit \
                "${QMAIL_INJECT} -H --" \
                "does fully qualify the To: recipient."
}

main "$@"
```

**Comment by DerDakon** [comment]
Awesome. Now we just need a replacement qmail-queue that verifies if the address is expanded or not and put that into QMAIL_QUEUE, and a bit of magic for the Makefile so it can run as a unittest.

**Comment by schmonz** [comment]
Working on it :-)

**Comment by schmonz** [comment]
Work in progress on [schmonz-inject-recipient-qualification-tests](https://github.com/notqmail/notqmail/pull/new/schmonz-inject-recipient-qualification-tests).

**Comment by DerDakon** [comment]
I would suggest a different approach here: given that we all have few time, and that we would like to get the test done right and so on: let's just do this without (merged) tests. We have done the tests, and we are confident that this now works. Let's just merge it, the work on the tests will not stop because of we have this merged or even released. This would remove the main blocker for a 1.09 release IMHO and we can go forward with that.
