### ISSUE TITLE
[ENHANCEMENT] Expand the "Why not Postfix?" Section

### ISSUE THREAD

**Issue by FreddyMarsden** [notqmail/notqmail#156]
Currently the '[Why not Postfix?](https://github.com/notqmail/notqmail/wiki#why-not-postfix)' section simply says:

> Postfix is very good. We also really like qmail.

For those trying to chose between the two, this doesn't inspire people (or at least me personally) to use the product. Perhaps a more in depth comparison could be used, or even what features are available in NotQmail over Postfix.

**Comment by twopir** [comment]
the most powerful feature of qmail-type systems, imo, is the `.qmail` file's [cascading lookup behavior for extension addresses](http://untroubled.org/ezmlm/man/man5/dot-qmail.5.html#lbAF), which enables [ezmlm](http://untroubled.org/ezmlm/), as well as a lot of filtering and other flexibility.

**Comment by FreddyMarsden** [comment]
This should probably be mentioned then...

**Comment by schmonz** [comment]
I’ve updated “Why not Postfix” to add some text adapted from [Lobste.rs discussion of notqmail’s initial release](https://lobste.rs/s/kvsqqr/notqmail_1_07_portability_correctness#c_3cvz3z). In short, at present, I think it’s reasonable for you not to be inspired to choose notqmail over Postfix. We’d be happy to have you try notqmail, of course! (And if you do, we’d be happy to hear how it goes — good, bad, confusing, etc.)

Thanks for this report!
