### ISSUE TITLE
"Use of a standard library function that is not thread-safe" (CodeQL #1 and #2)

### ISSUE THREAD

**Issue by schmonz** [notqmail/notqmail#194]
CodeQL wants us to know that [two](https://github.com/notqmail/notqmail/security/code-scanning/1) [places](https://github.com/notqmail/notqmail/security/code-scanning/2) in `predate.c` are not thread-safe:

- Line 60 `gmtime()`
- Line 69 `localtime()`

`predate` is a tiny client program, and seems quite unlikely to me to be ever made multi-threaded or copied for use in some other multi-threaded program.

OTOH, if it's portable to just use the `_r` variants, maybe we should just do that.

On the third hand, is this a program we can announce intent to delete? In-tree, it's used only by `datemail`, a tiny wrapper around `sendmail` -- and then `datemail` is used in-tree only as the answer to FAQ 6.1 about time zones with BSD `mail(1)`.

Two somewhat coupled decisions here:

1. Fix CodeQL report by dismissing these reports, or by switching to `_r`?
2. Plan to remove `predate` and/or `datemail` after 1.09, or plan to keep them?

**Comment by leahneukirchen** [comment]
Nothing in qmail is using threads, so these warnings should just be disabled.

**Comment by DerDakon** [comment]
I second that, and if we after a second look decide that this is just 1980'ies compatibility stuff, then let it die.

**Comment by schmonz** [comment]
Dismissed the alerts. #193 is the only other open CodeQL issue.
