### ISSUE TITLE
"qmail" package installation destroys Debian systems

### ISSUE THREAD

**Issue by bjt-user** [notqmail/notqmail#214]
"sudo apt install qmail" destroyed my Debian installation.
First it crashed, then I rebooted into command line but everything is very slow, no internet, startx and gnome don't work. I had to reinstall Debian.

In Ubuntu it shows error messages and my system froze, but survived after rebooting the computer.

**Comment by schmonz** [comment]
I'm sorry to hear this happened to you. I don't think any of the notqmail developers have been involved in creating Debian's qmail package, and I don't think Debian's qmail package makes use of notqmail at all. Please do report the bug you encountered (with more details if you have the patience for it) to the Debian folks. Looks like their instructions for doing so are [here](https://www.debian.org/Bugs/Reporting).

Some of us _have_ been involved in the [notqmail packages at OpenBuildService](https://build.opensuse.org/project/show/home:notqmail), which includes Debian and Ubuntu. If you try those, reporting failure (or success) would be appropriate here.

**Comment by bjt-user** [comment]
Ok, sorry I thought this was the repository for qmail.
