### ISSUE TITLE
Upgrade from qmail to notqmail 

### ISSUE THREAD

**Issue by lastsamurai26** [notqmail/notqmail#228]
Is it possible to update from the original Debian Qmail package to the NotQmail package?

since I recently upgraded from Buster to Bullseye, I wanted to go to notqmail now.

or is it better to purge Qmail and reinstall completely ? 

Is there currently a deb package for bullseye or do i have to build it from source ?

**Comment by mbhangui** [comment]
> Is it possible to update from the original Debian Qmail package to the NotQmail package?
> 
> since I recently upgraded from Buster to Bullseye, I wanted to go to notqmail now.
> 
> or is it better to purge Qmail and reinstall completely ?

apt will not allow you to install two packages referring to binary/files with the same paths. So the only option is is to remove currently installed debian qmail package and then install notqmail debian package. Hopefully removing the current qmail package using apt doesn't remove your current configuration files. Best is to backup your entire /var/qmail directory before removal of the qmail package. You can get help on the Libera Chat's #qmail IRC channel if you have doubts and need help.

> 
> Is there currently a deb package for bullseye or do i have to build it from source ?

I just enabled the build for bullseye. There are two methods supported by this [Repository](https://software.opensuse.org//download.html?project=home%3Anotqmail&package=notqmail)

**1. Added bullseye repository for notqmail**

```
echo 'deb http://download.opensuse.org/repositories/home:/notqmail/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/home:notqmail.list
curl -fsSL https://download.opensuse.org/repositories/home:notqmail/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_notqmail.gpg > /dev/null
sudo apt update
sudo apt install notqmail
```

**2. Grab the debian package**

Dowload the package from [here](https://download.opensuse.org/repositories/home:/notqmail/Debian_11/amd64/notqmail_1.08-1.1+10.1_amd64.deb).

**Comment by DerDakon** [comment]
> Best is to backup your entire /var/qmail directory before removal of the qmail package.

If uninstalling the package and installing notqmail instead removes files that you still need, make sure to not restore the binaries from that archive if you want to stick with notqmail. All other files should be fine.

**Comment by lastsamurai26** [comment]
Thank you. 
I will test it, but I think it's the best idea to backup the configs and delete all data via apt purge and then reinstall. 

I will keep you up to date

**Comment by mrtrev** [comment]
Was your installation successful?

**Comment by lastsamurai26** [comment]
I have not tried it again, but my last attempt failed because netqmail did not start with the system. I have therefore left it for now and will test it again in a VM but the case can be closed.

**Comment by schmonz** [comment]
Thanks for letting us know.

When you come back to this, if you can, please take notes:

- Which commands you’re trying
- What happens when you run them
- Any cases where the result differs from what you were expecting

If you still run into trouble, your notes will help us figure out what we need to fix. And once everything does work, we’d love to borrow your notes and turn them into documentation for other folks considering an upgrade to notqmail.
