### ISSUE TITLE
suggest options for dealing with Google & Yahoo's latest?

### ISSUE THREAD

**Issue by schmonz** [notqmail/notqmail#262]
[Google](https://blog.google/products/gmail/gmail-security-authentication-spam-protection/) and [Yahoo](https://senders.yahooinc.com/best-practices/) have just tightened their criteria for accepting mail, for senders above a certain volume threshold.

We're a ways off from integrating support for SPF, DKIM, DMARC, ARC, etc. Should we offer some pointers to external tooling that can help in the meantime?

**Comment by schmonz** [comment]
On reflection with @mbhangui, here's what we should do for 1.09:

1. Not offer guidance. People have survived until now with their qmail installations, and are looking to us to eventually merge functionality, not suggest workarounds for missing functionality. So we didn't land DKIM (etc.) in time for February 2024's BigCo changes. Oh well.
2. Yes add @mbhangui's patch [as documented by](https://notes.sagredo.eu/en/qmail-notes-185/configuring-dkim-for-qmail-92.html) @sagredo-dev as a branch in [our collection of popular patch branches](https://notqmail.org/patches/)

Getting messages accepted these days strongly suggests SPF (adding a DNS record), DKIM-signing outbound messages (e.g., with this patch branch-to-be), and DMARC (adding a DNS record).

**Comment by DerDakon** [comment]
I added the patch here: https://github.com/notqmail/notqmail/tree/patches/netqmail/dkim

@mbhangui I put 2 cleanup commits on top that you may want to include in a new version whenever you do one. But to me these changes are no reason to do a new release.

**Comment by mbhangui** [comment]
> I added the patch here: https://github.com/notqmail/notqmail/tree/patches/netqmail/dkim
> 
> @mbhangui I put 2 cleanup commits on top that you may want to include in a new version whenever you do one. But to me these changes are no reason to do a new release.

I have applied your changes locally. Regarding whitespace, I find lot more files have the extra whitespace at the end and which has been there right from the beginning of qmail-1.03. Not going to touch them as they will make the patch unwieldly
