### ISSUE TITLE
"TOCTOU" in instchown.c

### ISSUE THREAD

**Issue by schmonz** [notqmail/notqmail#263]
The Security tab shows a few [TOCTOU in instchown.c](https://github.com/notqmail/notqmail/security/code-scanning/9). I vaguely recall having seen and discussed this before, but can't find it. Worth taking the analyzer's advice, or should we dismiss the alerts?

**Comment by DerDakon** [comment]
No, this is totally pointless. These are files we just installed. And I can't find a check of existence at the place this is pointing to, it is just doing ```chown()``` and reports error And before it does ```chmod()``` and reports error..
