### ISSUE TITLE
notqmail.org should redirect with a 307, not 301.

### ISSUE THREAD

**Issue by alanpost** [notqmail/notqmail#41]
Inspired by #39, where we publish our homepage in our SMTP protocol negotiation.  Here are the HTTP headers for that request:

    $ curl -D- https://notqmail.org/
    HTTP/1.1 301 Moved Permanently
    Location: https://github.com/notqmail/notqmail/wiki
    Content-Length: 0
    Date: Mon, 22 Jul 2019 00:45:48 GMT
    Server: lighttpd/1.4.54

Note we redirect to our GitHub wiki using a 301 status code.  I'd like this to be changed to 307 Temporary Redirect.

It's existentially possible, if not likely, that we'll want a landing page in the future that isn't permanently tied to our GitHub wiki page.  Using 307 instead of 301 will change the way a browser caches the response, in favor of making it easier to change where the site redirects to.

**Comment by schmonz** [comment]
Now I know how to get lighttpd to say 307. Done!

**Comment by alanpost** [comment]
Thank you, looks good to me:

    $ curl -D- https://notqmail.org/
    HTTP/1.1 307 Temporary Redirect
    Location: https://github.com/notqmail/notqmail/wiki
    Content-Length: 0
    Date: Mon, 22 Jul 2019 01:28:05 GMT
    Server: lighttpd/1.4.54
