### ISSUE TITLE
Missing closing parenthesis in 1.07 release description

### ISSUE THREAD

**Issue by jlmuir** [notqmail/notqmail#66]
The last item (Remove vfork(), fixing macOS runtime) in the [notqmail 1.07 release description](https://github.com/notqmail/notqmail/releases) is missing a closing parenthesis for the referenced PR.

I know this is trivial, and I know that I can edit it myself, but I don't know if doing so would mess up the official release.  Will undesirable things happen if I fix it (i.e., click Edit, fix the description, and click "Update release")?

**Comment by DerDakon** [comment]
No, this is just text on the web, you are free to edit this.

**Comment by jlmuir** [comment]
OK, thanks!  Fixed.
